#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export $(grep -v '^#' .env | xargs)

echo "⚡ Running Laravel Pint..."

STAGED_PHP_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '\.php$' || true)

if [ -n "$STAGED_PHP_FILES" ]; then
    echo "Staged PHP Files"
    echo "$STAGED_PHP_FILES"
    docker run --rm \
        -u "$(id -u):$(id -g)" \
        -v "$(pwd):/var/www/html" \
        -w /var/www/html \
        php ./vendor/bin/pint --preset laravel $STAGED_PHP_FILES
fi

#echo "🔍 Running eslint..."
#yarn lint-staged

#echo "🎨 Running prettier..."
#yarn prettier

exit 0
