name: Deploy to Prod

on:
  workflow_run:
    workflows: ["Tests"]
    branches: [master]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env file
        run: |
          touch .env
          echo DEPLOY_HOST="${{ secrets.ZALOSPACE_HOST }}" >> .env
          echo DEPLOY_USER="${{ secrets.ZALOSPACE_USER }}" >> .env
          echo DEPLOY_DIR="${{ secrets.ZALOSPACE_DIR }}" >> .env

      - name: Use laravel environment
        uses: laravelfans/laravel

      - name: Deploy Site
        run: |
          composer global require laravel/envoy
          php ~/.composer/vendor/bin/envoy run deploy
